# Generated by Django 5.0.6 on 2024-07-15 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('aktifmi', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('yetki', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stajyerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('bolum', models.CharField(max_length=50)),
                ('dal', models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End')], max_length=20)),
                ('kacyillik', models.CharField(choices=[('lisans', 'Lisans (4 yıl)'), ('onlisans', 'Önlisans (2 yıl)')], max_length=20)),
                ('tamamdevam', models.CharField(choices=[('tamam', 'Tamamladı'), ('devam', 'Okuyor')], max_length=20)),
                ('donem', models.CharField(choices=[('uzun', 'Uzun dönem'), ('kisa', 'Kısa dönem')], max_length=20)),
                ('biografi', models.TextField()),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kiz', 'Kız')], max_length=10)),
                ('telefon', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('aktif', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('register', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.register')),
            ],
        ),
    ]
