# Generated by Django 5.0.6 on 2024-07-17 13:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('surname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('aktifmi', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('yetki', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Kurucu', 'Kurucu')], max_length=20)),
                ('hesapTarih', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stajyerinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bolum', models.CharField(max_length=50)),
                ('dal', models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End')], max_length=20)),
                ('kacyillik', models.CharField(choices=[('lisans', 'Lisans (4 yıl)'), ('onlisans', 'Önlisans (2 yıl)')], max_length=20)),
                ('tamamdevam', models.CharField(choices=[('tamam', 'Tamamladı'), ('devam', 'Okuyor')], max_length=20)),
                ('donem', models.CharField(choices=[('uzun', 'Uzun dönem'), ('kisa', 'Kısa dönem')], max_length=20)),
                ('biografi', models.TextField()),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kiz', 'Kız')], max_length=10)),
                ('telefon', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('aktif', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('register', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.register')),
            ],
        ),
        migrations.CreateModel(
            name='VerilenGorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=100)),
                ('taskcontent', models.TextField()),
                ('taskimage', models.ImageField(blank=True, null=True, upload_to='tasks/')),
                ('taskfile', models.FileField(blank=True, null=True, upload_to='tasks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='main.register')),
                ('assigned_to', models.ManyToManyField(related_name='tasks', to='main.register')),
            ],
        ),
    ]
