# Generated by Django 5.0.6 on 2024-07-18 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TamamlananGorev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='completed_tasks/')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.verilengorev')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.register')),
            ],
        ),
    ]
