# Generated by Django 5.0.6 on 2024-07-18 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_register_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlogin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.register'),
        ),
    ]
