# Generated by Django 5.0.6 on 2024-07-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userlogin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_special_day', models.BooleanField(default=False)),
                ('last_checked', models.DateField(auto_now=True)),
            ],
        ),
    ]
