# Generated by Django 5.0.6 on 2024-07-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_userresponse_selected_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='completed_tasks',
            field=models.IntegerField(default=0),
        ),
    ]
