# Generated by Django 5.0.6 on 2024-07-12 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('password2', models.CharField(max_length=50)),
                ('aktifmi', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stajyerinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=50)),
                ('bolum', models.CharField(max_length=50)),
                ('dal', models.CharField(choices=[('frontend', 'Front-End'), ('backend', 'Back-End')], max_length=20)),
                ('kacyillik', models.CharField(choices=[('lisans', 'Lisans (4 yıl)'), ('onlisans', 'Önlisans (2 yıl)')], max_length=20)),
                ('tamamdevam', models.CharField(choices=[('tamam', 'Tamamladı'), ('devam', 'Okuyor')], max_length=20)),
                ('donem', models.CharField(choices=[('uzun', 'Uzun dönem'), ('kisa', 'Kısa dönem')], max_length=20)),
                ('biografi', models.TextField()),
                ('cinsiyet', models.CharField(choices=[('erkek', 'Erkek'), ('kiz', 'Kız')], max_length=10)),
                ('telefon', models.CharField(max_length=15)),
                ('mail', models.EmailField(max_length=254)),
                ('aktif', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
