# Generated by Django 5.0.6 on 2024-07-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stajyerinfo',
            name='dal',
            field=models.CharField(choices=[('Front-End', 'Front-End'), ('Back-End', 'Back-End')], max_length=20),
        ),
    ]
