# Generated by Django 5.0.6 on 2024-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sertac', '0002_alter_register_aktifmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='anasayfa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
